services:
  database:
    image: 'postgres:latest'
    ports:
      - 5432:5432

    volumes:
    # persistent volume
    - ${PWD}/db/db-data/:/var/lib/postgresql/data/
    # init script
    - ${PWD}/db/init.sql:/docker-entrypoint-initdb.d/init.sql

    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_SECRET}
      POSTGRES_DB: ${DB_NAME}